/**
 * @author: Polyakov Daniil
 * @mail: arjentix@gmail.com
 * @github: Arjentix
 * @date: 30.10.2020
 * @copyright: Copyright 2020 Polyakov Daniil
 */

#include "ng.h"

#include <random>

namespace {

/**
 * @brief   Possible values for N and g in SRP-6 algorithm
 * 
 * @details Generated by utils/ng_generator.py
 */
extern const std::vector<std::pair<int, int>> kNg;

}  // namespace


std::pair<int, int> GenerateNAndG() {
    std::random_device r;
    std::default_random_engine generator(r());
    std::uniform_int_distribution<int> distribution(0, kNg.size());

    return kNg.at(distribution(generator));
}


namespace {

const std::vector<std::pair<int, int>> kNg = {
    {5, 2},
    {7, 3},
    {11, 2},
    {23, 5},
    {47, 5},
    {59, 2},
    {83, 2},
    {107, 2},
    {167, 5},
    {179, 2},
    {227, 2},
    {263, 5},
    {347, 2},
    {359, 7},
    {383, 5},
    {467, 2},
    {479, 13},
    {503, 5},
    {563, 2},
    {587, 2},
    {719, 11},
    {839, 11},
    {863, 5},
    {887, 5},
    {983, 5},
    {1019, 2},
    {1187, 2},
    {1283, 2},
    {1307, 2},
    {1319, 13},
    {1367, 5},
    {1439, 7},
    {1487, 5},
    {1523, 2},
    {1619, 2},
    {1823, 5},
    {1907, 2},
    {2027, 2},
    {2039, 7},
    {2063, 5},
    {2099, 2},
    {2207, 5},
    {2447, 5},
    {2459, 2},
    {2579, 2},
    {2819, 2},
    {2879, 7},
    {2903, 5},
    {2963, 2},
    {2999, 17},
    {3023, 5},
    {3119, 7},
    {3167, 5},
    {3203, 2},
    {3467, 2},
    {3623, 5},
    {3779, 2},
    {3803, 2},
    {3863, 5},
    {3947, 2},
    {4007, 5},
    {4079, 11},
    {4127, 5},
    {4139, 2},
    {4259, 2},
    {4283, 2},
    {4547, 2},
    {4679, 11},
    {4703, 5},
    {4787, 2},
    {4799, 7},
    {4919, 13},
    {5087, 5},
    {5099, 2},
    {5387, 2},
    {5399, 7},
    {5483, 2},
    {5507, 2},
    {5639, 7},
    {5807, 5},
    {5879, 11},
    {5927, 5},
    {5939, 2},
    {6047, 5},
    {6599, 13},
    {6659, 2},
    {6719, 11},
    {6779, 2},
    {6827, 2},
    {6899, 2},
    {6983, 5},
    {7079, 7}
};

}  // namespace
